export const genericImportCsv = `Flight Date,Tail Number,Departure,Destination,Duration,Day,Night,Pilot in Command,Co-pilot,Student Name,Role,Passengers,Notes
2026-08-01,c fxyz,CEN4,CYBW,1:30,1.2,0.3,1.5,0,Training Student,instructor,Sample Passenger,Sanitized fixture
03/04/2026,C-FXYZ,CYBW,CEN4,1.0,1.0,0,1.0,0,,pic,,Ambiguous date`;

export const applicationFixtureFlight = {
  id: "fixture-flight",
  date: "2026-08-01",
  aircraftId: "fixture-aircraft",
  from: "CEN4",
  to: "CYBW",
  route: "DCT",
  totalTime: 1.5,
  dayTime: 1.2,
  pic: 1.5,
  sic: 0,
  solo: 0,
  dualReceived: 0,
  dualGiven: 1.5,
  crossCountry: 0.7,
  night: 0.3,
  actualInstrument: 0.2,
  simulatedInstrument: 0.1,
  simTime: 0,
  dayTakeoffs: 1,
  nightTakeoffs: 0,
  dayLandings: 1,
  nightLandings: 0,
  approaches: 1,
  holds: 0,
  remarks: "Sanitized fixture",
  sourceAircraftText: "c fxyz",
  myRole: "instructor",
  legalPicName: "Test Pilot",
  primaryCrewName: "Training Student",
  primaryCrewRole: "student",
  instructorName: "Test Pilot",
  passengers: ["Sample Passenger"],
  copilotCreditConfirmed: false,
} as const;
